### ISSUE TITLE
Error message while in another app

### ISSUE THREAD

**Issue by Wolf68k** [yuliskov/SmartTubeNext#1264]
I was watching a movie in HBOMax and an error message mentioning a log file came up a few times. I ignored it for the time being. When I loaded back into STN stable 13.81 I got it again. Took some doing but finally got a copy of the file that I could submit
[ModernClientData.txt](https://github.com/yuliskov/SmartTubeNext/files/7947890/ModernClientData.txt)

Fire TV OS 7.2.6.8

**Comment by DrOakfield** [comment]
I have been experiencing this problem since yesterday evening as well, on my Nvidia Shield TV Pro 2019. First in HBO Max and today in Plex. I think there might be between 20-30 minutes between each error message. Rebooting my device made the message appear as soon as the start menu was opened.
![IMG_20220127_142643 resize1](https://user-images.githubusercontent.com/44894048/151378116-91212055-e288-4f94-a961-0722ff6efab7.jpg)


The file referenced in the error: 
[ModernClientData.txt](https://github.com/yuliskov/SmartTubeNext/files/7951118/ModernClientData.txt)

Kudos on a great app by the way.

SHIELD Experience 9.0.0 (33.1.0.236)

**Comment by dimitritholen** [comment]
Same as above. Also on Nvidia Shield

**Comment by Dummyxl** [comment]
Als appears on sony Bravia tv.  Every 30 minutes or so the toast message comes up. No matter what I'm doing on my tv. (mp4/Netflix /digital tv)

**Comment by Wolf68k** [comment]
Since updating to Stable 14.06 I haven't seen anything.

**Comment by dudeins** [comment]
> Since updating to Stable 14.06 I haven't seen anything.

Nope, still the same error message on 14.06.

**Comment by Alteus** [comment]
Same error on Mi Box S. #
[ModernClientData.txt](https://github.com/yuliskov/SmartTubeNext/files/7954007/ModernClientData.txt)

**Comment by Alteus** [comment]
#1262

**Comment by kabukimurder** [comment]
This happens on both my Shield and Chromecast w Google tv.

**Comment by roddsrod** [comment]
I use it on Philips TV with native Android TV.
I had the log error message with almost every video I launched, but since it played fine anyway and the message disappeared quickly it didn't bother me that much.
A couple days ago it randomly popped up the log error message even when using another app like Netflix or Kodi as other people do report too, a bit annoying but whatever.
It now just popped up again on top of my HDMI input while I was playing Xbox o_O

**Comment by RKCRLR** [comment]
I updated to the beta version and it fixed the problem.  There is now a 14.11 release out now that has that change rolled in.

**Comment by jeepy321** [comment]
I have updated to 14.11 on Nvidia Shield hopefully this fixes it

**Comment by Staubgeborener** [comment]
Last [commit](https://github.com/yuliskov/SmartTubeNext/commit/de4ff6429af5ce42564b7e5813bcba56020050fe) fixes this issue with the version 14.16. You can simply use the default update function inside the app.

**Comment by Dummyxl** [comment]
Updated on my Sony, i think it is fixed

**Comment by kabukimurder** [comment]
This seems to have come and gone without any updates. How come? Is the app connecting to any externa sources that has been modified since this was reported?

**Comment by Wolf68k** [comment]
Fixed and closed

**Comment by mvallerie** [comment]
Updated to 14.16 on my shield pro, unfortunately, I'm still getting the same error (every 15 mins or so). I also tried to wipe cache / reset data / reinstall app, which didn't help.

**Comment by lordradon** [comment]
Still happening here. Nvidia shield

**Comment by mvegetto** [comment]
Same here...
