### ISSUE TITLE
Unknown integer error, unknown error null etc

### ISSUE THREAD

**Issue by CSGOTUT** [yuliskov/SmartTubeNext#2905]
The video keeps refreshing when it errors.

**Comment by CSGOTUT** [comment]
Don't have backup, just installed.

**Comment by Darl-h** [comment]
Errors galore on my FireTV Cube V3, with SmartTube. Mostly 'Unknown error  Invalid NAL length'. Seems most prevalent on recently uploaded videos, and never errors on Live Streams.

**Comment by CSGOTUT** [comment]
I have variety of errors, mostly there is something about integer being wrong.

**Comment by dillyhammer** [comment]
All manner of errors - many during a single video.

unknown error null
integer size > 2147483647 (unsupported)
invalid integer size

These appear in a small pill-shaed grey box at the bottom of a black screen.
Sometimes it's just a black screen, no message.

The app is virtually unusable.
I'm going to try and delete the current config, and if that doesn't work then a resinstall.
If both of those fail I'll need to find an alternative app until this gets fixed.

**Comment by CSGOTUT** [comment]
> All manner of errors - many during a single video.
> 
> unknown error null integer size > 2147483647 (unsupported) invalid integer size
> 
> These appear in a small pill-shaed grey box at the bottom of a black screen. Sometimes it's just a black screen, no message.
> 
> The app is virtually unusable. I'm going to try and delete the current config, and if that doesn't work then a resinstall. If both of those fail I'll need to find an alternative app until this gets fixed.

Same thing , if you find good alternative , please let me know.

**Comment by yrivardmulrooney** [comment]
I'm running into the same issue on two different chromecast with google tv devices. The app is pretty much unusable, there are multiple different errors that pop up when trying to play videos (integer size, null errors, and others that I can't remember right this moment).

I've tried deleting cache for the app, then deleting the whole app data, and finally uninstalling and reinstalling, nothing fixed the issue. The beta version also seems affected, I tried it to see if that would resolve the issue.

I'm guessing YouTube rolled out an incompatible change or something, it started occurring out of the blue yesterday evening and I had been running the most recent version of the stable app for at least a few days at that point.

**Comment by yrivardmulrooney** [comment]
For some reason, today, without changing anything, everything seems to be working properly without errors on my side. I don't know if this will come back or not, but all is well for now.

**Comment by ErolTR** [comment]
Still broken for me on latest 19.45 update.
Get a bunch of errors on some videos

**Comment by dillyhammer** [comment]
Errors disappeared briefly yesterday, then came back.
I deleted cache and data, uninstalled the app, then reinstalled.
The first few videos I played went normally.
Then, the errors came back with a vengeance.
App remains unuseable.
Such a shame - one of the best apps out there, then this happens.
No word from the developer.
I see commits to the code, but nothing that addresses this.

**Comment by CSGOTUT** [comment]
Yesterday was fine for me , with just music going on autoplay for like 4 hours, didint notice an error but there may aswell had been some i just didint pay attention to.

Havent had the error where video totally craps out tho, as i had few days ago. The time it totally crashed i had to force close smarttube for it to be able to play again.

**Comment by hemstoc** [comment]
In addition to "error null" and "invalid integer size" (of various sizes) errors I'm also seeing "No valid varint length mask found", which could be coming from [VarintReader.java#L91](https://github.com/yuliskov/SmartTubeNext/blob/master/exoplayer-amzn-2.10.6/library/core/src/main/java/com/google/android/exoplayer2/extractor/mkv/VarintReader.java#L91) or [MatroskaExtractor.java#L1110](https://github.com/yuliskov/SmartTubeNext/blob/master/exoplayer-amzn-2.10.6/library/core/src/main/java/com/google/android/exoplayer2/extractor/mkv/MatroskaExtractor.java#L1110). 

Both of those files live in exoplayer. Assuming we are using https://github.com/google/ExoPlayer, I wonder if upgrading this dependency to a newer version could resolve these errors?

**Comment by josharghhh** [comment]
So removed and re installed with beta. Issues were gone for a day before appearing again.

**Comment by Darl-h** [comment]
Have done a factory reset on my FireCube Gen3 and then clean install of 'Stable' SmartTube - still getting various Integer and Out of Bounds errors. Uninstalled 'Stable' and then install 'Beta' and still get the errors.

**Comment by ErolTR** [comment]
Is there any way to capture and review logs ourselves? I can take a crack at fixing this later if dev doesn't respond. 

I've gone back to using... stock YouTube. It's that bad right now. Like 8 out of 10 videos have this issue, plays for maybe 30 seconds to a minute and then begins to error.

Sometimes you can back out of the video and then open it again and it'll be good the rest of the time, other times it'll keep erroring every 10 seconds.

**Comment by Peaceout32** [comment]
We need to figure out what we have in common that the others don't... This issue is pissing me off lol

**Comment by ErolTR** [comment]
I'm on a TCL Android TV... personally I don't think the specific equipment we're using really matters, this is a software glitch.

Theres a chance this could be network related, possibly some kind of routing failure maybe?

My internet is 1.5gbps fibre from Bell, near the Toronto area. If theres a few of us with the same ISP or in the same area, it could point to a routing issue. Otherwise, probably something code related.

**Comment by Peaceout32** [comment]
Same internet here in Qc. Using NextDNS.

**Comment by colin19889** [comment]
Same issue, uninstall and reinstall fixed it. Seems to be software related vs. anything that was changed on YouTube's side.

**Comment by ErolTR** [comment]
I'll try clearing data + reinstalling when I get home and update on if its resolved

**Comment by Peaceout32** [comment]
> I'll try clearing data + reinstalling when I get home and update on if its resolved

Done that a few times... It always comes back

**Comment by Affondles** [comment]
Clearing data + reinstalling has not worked for me, both on stable and beta.

**Comment by sia84** [comment]
I am seeing the same issue on nvidia shield device. Reinstalling the app did not fix the issue

**Comment by Peaceout32** [comment]
This is really a weir error. I've been using the app pretty much it all day today without any errors. Haven't changed anything at all.

**Comment by dillyhammer** [comment]
Day 3 with no errors.
So this is what I think happened.
I think the developer of this app turned on some debug setting on his Google developer account, for whatever reason - maybe to add a new feature or something, and that was what initiated the errors suddenly, without warning or anything.
He does what he needs to do over the course of several days. 
For sure, he has seen this thread and has said or done nothing - that's the clue.
Then, work done, turns the setting off, errors go away.

Anyways.
I'm looking at adding AdBlock to my router. If successful, I can go back to using Google's native youtube app without ads.
Sure beats going through this nonsense. Sure glad I didn't pay for this.
It is free software, so if you're planning on using this, this instability is just something you'll have to learn to live site.

**Comment by sia84** [comment]
This issue is still not resolved for me. I am attaching the different error messages I’m getting here: 
![IMG_3175](https://github.com/yuliskov/SmartTubeNext/assets/20882902/94bdbef7-bd93-49b4-a0f5-b70ecd5de3a5)
![IMG_3173](https://github.com/yuliskov/SmartTubeNext/assets/20882902/8f5f935a-771c-43b0-89a2-e0e224a4a855)
![IMG_3172](https://github.com/yuliskov/SmartTubeNext/assets/20882902/3580558f-28b0-4f2a-939b-de9a9ff0f539)
![IMG_3171](https://github.com/yuliskov/SmartTubeNext/assets/20882902/b6146cf0-5a42-4db4-ac23-826c9ae388a0)

**Comment by ErolTR** [comment]
Error was gone for a few days, it's back again

**Comment by SyCoREAPER** [comment]
^Same errors as other posters. Null error followed by integer. 

ShieldTV. Wasn't having any issues until recently.

**Comment by ErolTR** [comment]
Still having this issue. App is unusable

**Comment by Ize-dev** [comment]
Still errors on latest stable and beta version in 2024, unusable

**Comment by colin19889** [comment]
> Still errors on latest stable and beta version in 2024, unusable

I've been using the stable version for months on an NVIDIA Shield and Google TVs with no issues whatsoever.

**Comment by djrarky** [comment]
I'm seeing this behaviour too on Google TV. Thought it was MTU size or similar, but I now don't believe it is.

Some videos play perfectly, others are unwatchable
